config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items
  resources :categories
  namespace :dashboard do
    resources :users
  end

  get '/search', to: 'search#index'
  get '/search/:id', to: 'search#show'

  root 'items#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items
  def self.search(search)
    where("name LIKE ?", "%#{search}%") 
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
  validates :code, uniqueness: true
  has_attached_file :avatar, styles: { medium: "500x500>"}, default_url: "/images/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def avatar_url
    self.avatar.url(:medium)
  end

  def self.search(search)
    where("name LIKE ?", "%#{search}%") 
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  if Rails.env.production?
   devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  else
    devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :registerable 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: [:show, :edit, :destroy, :update]
  before_action :authenticate_user!

  def index
    @categories = Category.paginate(page: params[:page], per_page: 10)
    if params[:search]
      @categories = Category.search(params[:search]).paginate(page: params[:page], per_page: 3).order("created_at DESC")
    else
      @categories = Category.paginate(page: params[:page], per_page: 3).order('created_at DESC')
    end
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      redirect_to categories_path, notice: "Se guardo Correctamente"
    else
      render 'new', notice: 'Oops, Ocurrio algun tipo de error'
    end
  end

  def show
  end

  def edit
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  def update
    if @category.update category_params
      redirect_to categories_path, notice: "Se actualizo"
    else
      redirect_to 'edit', notice: 'Algo salio Mál'
    end
  end
  
  private 
  def category_params
    params.require(:category).permit(:name)
  end
  def find_category
    @category = Category.find(params[:id])
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < ApplicationController
  before_action :set_dashboard_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /dashboard/users
  # GET /dashboard/users.json
  def index
    @dashboard_users = User.paginate(page: params[:page], per_page: 10)
  end

  # GET /dashboard/users/1
  # GET /dashboard/users/1.json
  def show
  end

  # GET /dashboard/users/new
  def new
    @dashboard_user = User.new
  end

  # GET /dashboard/users/1/edit
  def edit
  end

  # POST /dashboard/users
  # POST /dashboard/users.json
  def create
    @dashboard_user = User.new(dashboard_user_params)

    respond_to do |format|
      if @dashboard_user.save
        format.html { redirect_to dashboard_users_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @dashboard_user }
      else
        format.html { render :new }
        format.json { render json: @dashboard_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dashboard/users/1
  # PATCH/PUT /dashboard/users/1.json
  def update
    respond_to do |format|
      if @dashboard_user.update(dashboard_user_params)
        format.html { redirect_to dashboard_users_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @dashboard_user }
      else
        format.html { render :edit }
        format.json { render json: @dashboard_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboard/users/1
  # DELETE /dashboard/users/1.json
  def destroy
    @dashboard_user.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dashboard_user
      @dashboard_user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dashboard_user_params
       params.require(:user).permit(:email,:password)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: [:edit, :show, :update, :destroy]
  before_action :authenticate_user!
  def index
    @items = Item.paginate(page: params[:page], per_page: 10)
    if params[:search]
      @items = Item.search(params[:search]).paginate(page: params[:page], per_page: 3).order("created_at DESC")
    else
      @items = Item.paginate(page: params[:page], per_page: 3).order('created_at DESC')
    end
  end
  
  def new
    @item = Item.new
  end

  def edit
  end

  def create
    @item = Item.new params_item
    if @item.save
      redirect_to items_path, notice: 'Se logró guardar el item'
    else
      render 'new', notice: 'Ocurrió un error'
    end 
  end

  def show
  end

  def update
    if @item.update params_item
      redirect_to items_path, notice: 'Se logro actualizar correctamente'
    else
      render 'edit', notice: 'Ocurrió un error'
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path, notice: 'Se eliminó correctamente'
  end

  private
  def find_item
    @item = Item.find(params[:id])
  end
  def params_item
    params.require(:item).permit(:name, :code,  :description, :model, :category_id ,:price, :avatar)
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!
  def index
  end
  def show
    id = params[:id]
    item = Item.find_by code: id
    render json: item.to_json(methods: [:avatar_url])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard/users_helper.rb
module Dashboard::UsersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for @category, html: {class: 'col s12' } do |f|%>
  <% if @category.errors.any? %>
    <h2><%= pluralize(@category.errors.count, "Error") %></h2>
    <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><% msg %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="row">
    <div class="input-field col s12">
      <%= f.text_field :name, placeholder: 'Ingrese nombre...', class: 'validate'%>
      <%= f.label :name, 'Nombre' %>
    </div>
  </div>
  <div class="row">
    <%= f.submit 'Crear', class: 'btn waves-effect waves-light deep-orange' %>
  </div>   
<% end %>

app/views/categories/edit.html.erb
<h3>Editar Categorias</h3>

<%= render 'form' %>

<%= link_to 'Regresar', categories_path, class: 'waves-effect waves-light btn' %>

app/views/categories/index.html.erb
<h3>Categorias</h3>

<div class="row">
  <div class="col s6">
    <%= link_to new_category_path, class: 'btn-floating btn-large waves-effect waves-light red' do %>
      <i class="material-icons">add</i>
    <% end %>
  </div>
  <div class="col s6">
    <div class="col s6">
      <%= form_tag(categories_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Buscar Items" %>
        <%= button_tag "Buscar" , class: "btn waves-effect waves-light" do %>
          Buscar
          <i class="material-icons right">search</i>
        <% end %>
      <% end %> 
    </div>
  </div>
  <table class="striped bordered responsive-table ">
    <thead>
      <tr>
          <th data-field="id">#</th>
          <th data-field="name">Nombre</th>
          <th data-field="name">Acciones</th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.id %></td>
          <td><%= category.name %></td>  
          <td><%= link_to 'Editar',edit_category_path(category), class: 'light-blue  waves-effect waves-light btn' %> <%= link_to 'Eliminar',category_path(category), method: :delete, data: {confirm: 'Desea eliminar?'} ,class: 'red waves-effect waves-light btn' %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="row">
    <%= will_paginate @categories %>
  </div>
</div>

app/views/categories/new.html.erb
<h3>Crear nueva categoria</h3>

<%= render 'form' %>

<%= link_to 'Regresar', categories_path, class: 'waves-effect waves-light btn' %>

app/views/dashboard/users/_form.html.erb
<%= form_for [:dashboard, @dashboard_user], html: {class: 'col s12' } do |f|%>
  <% if @dashboard_user.errors.any? %>
    <h2><%= pluralize(@dashboard_user.errors.count, "Error") %></h2>
    <ul>
      <% @dashboard_user.errors.full_messages.each do |msg| %>
        <li><% msg %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="row">
    <div class="input-field col s12">
      <%= f.email_field :email, placeholder: 'Ingrese email...', class: 'validate'%>
      <%= f.label :email, 'Email' %>
    </div>
    <div class="input-field col s12">
      <%= f.password_field :password, placeholder: 'Ingrese contraseña...', class: 'validate'%>
      <%= f.label :password, 'Contraseña' %>
    </div>
  </div>
  <div class="row">
    <%= f.submit 'Guardar', class: 'btn waves-effect waves-light deep-orange' %>
  </div>   
<% end %>

app/views/dashboard/users/edit.html.erb
<h3>Editar Usuario</h3>

<%= render 'form' %>

<%= link_to 'Regresar', dashboard_users_path, class: 'waves-effect waves-light btn' %>

app/views/dashboard/users/index.html.erb
<h3>Usuarios</h3>

<div class="row">
  <div class="col s6">
    <%= link_to new_dashboard_user_path, class: 'btn-floating btn-large waves-effect waves-light red' do %>
      <i class="material-icons">add</i>
    <% end %>
  </div>
  <table class="striped bordered responsive-table ">
    <thead>
      <tr>
          <th data-field="id">Email</th>
          <th data-field="actions"> Acciones </th>
      </tr>
    </thead>
    <tbody>
      <% @dashboard_users.each do |dashboard_user| %>
        <tr>
          <td><%= dashboard_user.email %></td>
          <td><%= link_to 'Editar',edit_dashboard_user_path(dashboard_user), class: 'light-blue  waves-effect waves-light btn' %> <%= link_to 'Eliminar',dashboard_user_path(dashboard_user), method: :delete, data: {confirm: 'Desea eliminar?'} ,class: 'red waves-effect waves-light btn' %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="row">
  <%= will_paginate @dashboard_users %>
</div>


</div>

app/views/dashboard/users/new.html.erb
<h3>Crear Usuario</h3>

<%= render 'form' %>

<%= link_to 'Regresar', dashboard_users_path, class: 'waves-effect waves-light btn' %>

app/views/dashboard/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_dashboard_user_path(@dashboard_user) %> |
<%= link_to 'Back', dashboard_users_path %>

app/views/items/_form.html.erb
<%= form_for @item, html: {class: 'col s12', multipart: true} do |f| %>
  <% if @item.errors.any? %>
    <h4><%= pluralize(@item.errors.count, "Error")%></h4>
    <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="row">
    <%= f.file_field :avatar %>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.text_field :name, placeholder: 'Ingrese nombre...', class: 'validate' %>
      <%= f.label :name, 'Nombre' %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s6">
      <%= f.text_field :model, placeholder: 'Ingrese modelo...', class: 'validate' %>
      <%= f.label :model, 'Modelo' %>
    </div>
    <div class="input-field col s6">
      <%= f.collection_select :category_id, Category.all, :id, :name,  prompt: 'Selecciona una categoria' %>
      <%= f.label :category , 'Categoria' %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.number_field :price, placeholder: 'Ingrese precio...', class: 'validate' %>
      <%= f.label :price, 'Precio' %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.text_area :description, placeholder: 'Ingrese descripción...', class: 'validate materialize-textarea' %>
      <%= f.label :description, 'Descripción' %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.text_field :code, placeholder: 'Codigo', class: 'validate', id: 'input_barCode' %>
      <%= f.label :code, 'Codigo' %>
    </div>
    <img id="barcode">
  </div>
   <div class="row">
    <%= f.submit 'Crear', class: 'btn waves-effect waves-light deep-orange' %>
  </div>   
<% end %>

app/views/items/edit.html.erb
<h3>Editar item</h3>
<%= render 'form' %>

<%= link_to 'Regresar', items_path, class: 'waves-effect waves-light btn' %>

app/views/items/index.html.erb
<h3>Items</h3>

<div class="row"> 
  <table class="striped bordered responsive-table "> 
    <div class="col s6">
      <%= link_to new_item_path, class: 'btn-floating btn-large waves-effect waves-light red' do %>
        <i class="material-icons">add</i>
      <% end %>  
    </div>
    <div class="col s6">
      <%= form_tag(items_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Buscar Items" %>
        <%= button_tag "Buscar" , class: "btn waves-effect waves-light" do %>
          Buscar
          <i class="material-icons right">search</i>
        <% end %>
      <% end %>
    </div>

    <thead>
      <tr>
          <th data-field="id">#</th>
          <th data-field="name">Nombre</th>
          <th data-field="price">Precio</th>
          <th data-field="category"> Categoria </th>
          <th data-field="category"> Codigo de Barras </th>
          <th data-field="description"> Descripción </th>
          <th data-field="actions">Acciones</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= item.name %></td>
          <td><%= item.price %></td>  
          <td><%= item.category.name %></td>
          <td><%= item.code %></td>  
          <td><%= item.description %></td>  
          <td><%= link_to 'Ver', item_path(item), class: 'waves-effect waves-light btn' %> <%= link_to 'Editar',edit_item_path(item), class: 'light-blue  waves-effect waves-light btn' %> <%= link_to 'Eliminar',item_path(item), method: :delete, data: {confirm: 'Desea eliminar?'} ,class: 'red waves-effect waves-light btn' %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="row">
  <%= will_paginate @items %>
</div>

app/views/items/new.html.erb
<h3>Crear nuevo item</h3>
<%= render 'form' %>

<%= link_to 'Regresar', items_path, class: 'waves-effect waves-light btn' %>

app/views/items/show.html.erb
<div class="row"> 
  <div class="col s12">
    <%= image_tag @item.avatar.url(:medium) %>
    <h5>Nombre: </h5> <span class="card-title"><%= @item.name %></span>
    <h5>Descripción: </h5> <span class="card-title"><%= @item.description %></span>
    <h5>Model: </h5> <span class="card-title"><%= @item.model %></span>
    <h5>Categoria: </h5> <span class="card-title"><%= @item.category.name %></span>
    <h5>Precio: </h5> <span class="card-title"><%= @item.price %></span>
    <p style="display: none" id="codeitem"><%= @item.code %></p>
    <div>
      <h5> Código de barras</h5>
      <div id="contentPrint">
        <img width="250px" id="barcode_show"> 
      </div>
      <a id="printBarcode" class="waves-effect waves-light btn"><i class="material-icons left">print</i>Imprimir</a>
    </div>
    <br>
    <%= link_to 'Regresar', items_path, class: "btn waves-effect waves-light light-blue" %>
  </div>

</div>   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BarcodeProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'partials/header' %>
  <main class="container">
    <%= yield %>
  </main>
  <%= render 'partials/footer' %>
          
  

</body>
</html>

app/views/partials/_footer.html.erb
 <footer class="page-footer">
    <div class="footer-copyright">
        <div class="container">
        (c) BarcodeUCPS by Alumnos UCPS Logística 2015 Noche
        </div>
    </div>
 </footer>

app/views/partials/_header.html.erb
<nav class="light-blue lighten-1" role="navigation">
  <div class="nav-wrapper container" >
    <%= link_to 'BarcodeSoft UCPS-UNSA', root_path, class: 'brand-logo' %>
    <a href="#" data-activates="nav-mobile" class="button-collapse" id="button-collapseMenu"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <li><%= link_to 'Inicio', root_path %></li>
      <li><%= link_to 'Items', items_path %></li>
      <li><%= link_to 'Categorias', categories_path %></li>
      <li><%= link_to 'Usuarios', dashboard_users_path %></li>
      <li><%= link_to 'Buscar', search_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %></li>
      <% else %>
        
      <% end %>
    </ul>
    <ul class="side-nav" id="nav-mobile">
      <li><%= link_to 'Inicio', root_path %></li>
      <li><%= link_to 'Items', items_path %></li>
      <li><%= link_to 'Categorias', categories_path %></li>
      <li><%= link_to 'Buscar', search_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %></li>
      <% end %>
  </div>
</nav>

app/views/search/index.html.erb
<h4>Buscar</h4>
<div class="row">
  <div class="col s12">
    <input type="text" id="searchByBarCode">
  </div>
  <div id="contentItem">
    
  </div>
</div>